### ISSUE TITLE
Oneclic

### ISSUE THREAD

**Issue by pham-dat** [lemonwaysas/wordpress-woocommerce-lemonway-plugin#2]
@sirateck 
Quand je fais un paiement par oneclic, la commande reste à "Pending payment" dans le back de Wordpress alors que c'est bien passé dans le backoffice LW : 
![image](https://cloud.githubusercontent.com/assets/13848893/16231900/a142d09a-37c8-11e6-95d8-4ca79edebbe1.png)

**Comment by pham-dat** [comment]
@sirateck 
Tu as une idée pour ça ?

**Comment by sirateck** [comment]
Salut @Crocodile29292 ,

c'est corrigé. 
Release v1.0.8
